Squashed commit of deactivate-pages-2.6.37
commit ae162588df49db8748c3401ba7f8f3cc6c672d4a
Author: Steven Barrett <damentz@liquorix.net>
Date:   Thu Dec 30 21:58:42 2010 -0600

    mm: fix ClearPageReclaim oops with two audio streams

commit f7a7eed6e20f4edfe0ddeee98b91f5981d6225eb
Author: Minchan Kim <minchan.kim@gmail.com>
Date:   Tue Nov 30 00:23:21 2010 +0900

    Prevent activation of page in madvise_dontneed

    Now zap_pte_range alwayas activates pages which are pte_young &&
    !VM_SequentialReadHint(vma). But in case of calling MADV_DONTNEED,
    it's unnecessary since the page wouldn't use any more.

    Signed-off-by: Minchan Kim <minchan.kim@gmail.com>
    Acked-by: Rik van Riel <riel@redhat.com>
    Cc: KOSAKI Motohiro <kosaki.motohiro@jp.fujitsu.com>
    Cc: Johannes Weiner <hannes@cmpxchg.org>
    Cc: Nick Piggin <npiggin@kernel.dk>
    Cc: Mel Gorman <mel@csn.ul.ie>
    Cc: Wu Fengguang <fengguang.wu@intel.com>

    Changelog since v2:
     - remove unnecessary description
    Changelog since v1:
     - change word from promote to activate
     - add activate argument to zap_pte_range and family function

commit 84ffa59256a58b149b7660b7bdac421348e82ee7
Author: Minchan Kim <minchan.kim@gmail.com>
Date:   Mon Dec 6 02:29:12 2010 +0900

    Reclaim invalidated page ASAP

    invalidate_mapping_pages is very big hint to reclaimer.
    It means user doesn't want to use the page any more.
    So in order to prevent working set page eviction, this patch
    move the page into tail of inactive list by PG_reclaim.

    Please, remember that pages in inactive list are working set
    as well as active list. If we don't move pages into inactive list's
    tail, pages near by tail of inactive list can be evicted although
    we have a big clue about useless pages. It's totally bad.

    Now PG_readahead/PG_reclaim is shared.
    fe3cba17 added ClearPageReclaim into clear_page_dirty_for_io for
    preventing fast reclaiming readahead marker page.

    In this series, PG_reclaim is used by invalidated page, too.
    If VM find the page is invalidated and it's dirty, it sets PG_reclaim
    to reclaim asap. Then, when the dirty page will be writeback,
    clear_page_dirty_for_io will clear PG_reclaim unconditionally.
    It disturbs this serie's goal.

    I think it's okay to clear PG_readahead when the page is dirty, not
    writeback time. So this patch moves ClearPageReadahead.

    Signed-off-by: Minchan Kim <minchan.kim@gmail.com>
    Acked-by: Rik van Riel <riel@redhat.com>
    Acked-by: Mel Gorman <mel@csn.ul.ie>
    Cc: Wu Fengguang <fengguang.wu@intel.com>
    Cc: KOSAKI Motohiro <kosaki.motohiro@jp.fujitsu.com>
    Cc: Johannes Weiner <hannes@cmpxchg.org>
    Cc: Nick Piggin <npiggin@kernel.dk>

    Changelog since v3:
     - move page which ends up writeback in pagevec on inactive's tail
    	- suggested by Johannes

    Changelog since v2:
     - put ClearPageReclaim in set_page_dirty - suggested by Wu.

    Changelog since v1:
     - make the invalidated page reclaim asap - suggested by Andrew.

commit 64252f8c1fa0a2bb8a5e1445f57785f7363c720c
Author: Minchan Kim <minchan.kim@gmail.com>
Date:   Mon Dec 6 02:29:11 2010 +0900

    move memcg reclaimable page into tail of inactive list

    Golbal page reclaim moves reclaimalbe pages into inactive list
    to reclaim asap. This patch apply the rule in memcg.
    It can help to prevent unnecessary working page eviction of memcg.

    Cc: Balbir Singh <balbir@linux.vnet.ibm.com>
    Cc: KAMEZAWA Hiroyuki <kamezawa.hiroyu@jp.fujitsu.com>
    Cc: Rik van Riel <riel@redhat.com>
    Cc: KOSAKI Motohiro <kosaki.motohiro@jp.fujitsu.com>
    Signed-off-by: Minchan Kim <minchan.kim@gmail.com>

commit abcd98d3e9faccc9b24d8c51d6143d4dd60ee9fc
Author: Minchan Kim <minchan.kim@gmail.com>
Date:   Mon Dec 6 02:29:10 2010 +0900

    deactivate invalidated pages

    Recently, there are reported problem about thrashing.
    (http://marc.info/?l=rsync&m=128885034930933&w=2)
    It happens by backup workloads(ex, nightly rsync).
    That's because the workload makes just use-once pages
    and touches pages twice. It promotes the page into
    active list so that it results in working set page eviction.

    Some app developer want to support POSIX_FADV_NOREUSE.
    But other OSes don't support it, either.
    (http://marc.info/?l=linux-mm&m=128928979512086&w=2)

    By other approach, app developers use POSIX_FADV_DONTNEED.
    But it has a problem. If kernel meets page is writing
    during invalidate_mapping_pages, it can't work.
    It is very hard for application programmer to use it.
    Because they always have to sync data before calling
    fadivse(..POSIX_FADV_DONTNEED) to make sure the pages could
    be discardable. At last, they can't use deferred write of kernel
    so that they could see performance loss.
    (http://insights.oetiker.ch/linux/fadvise.html)

    In fact, invalidation is very big hint to reclaimer.
    It means we don't use the page any more. So let's move
    the writing page into inactive list's head.

    Why I need the page to head, Dirty/Writeback page would be flushed
    sooner or later. It can prevent writeout of pageout which is less
    effective than flusher's writeout.

    Originally, I reused lru_demote of Peter with some change so added
    his Signed-off-by.

    Reported-by: Ben Gamari <bgamari.foss@gmail.com>
    Signed-off-by: Minchan Kim <minchan.kim@gmail.com>
    Signed-off-by: Peter Zijlstra <peterz@infradead.org>
    Acked-by: Rik van Riel <riel@redhat.com>
    Reviewed-by: KOSAKI Motohiro <kosaki.motohiro@jp.fujitsu.com>
    Cc: Wu Fengguang <fengguang.wu@intel.com>
    Cc: Johannes Weiner <hannes@cmpxchg.org>
    Cc: Nick Piggin <npiggin@kernel.dk>
    Cc: Mel Gorman <mel@csn.ul.ie>

    Andrew. Before applying this series, please drop below two patches.
     mm-deactivate-invalidated-pages.patch
     mm-deactivate-invalidated-pages-fix.patch

    Changelog since v3:
     - Change function comments - suggested by Johannes
     - Change function name - suggested by Johannes
     - add only dirty/writeback pages to deactive pagevec

    Changelog since v2:
     - mapped page leaves alone - suggested by Mel
     - pass part related PG_reclaim in next patch.

    Changelog since v1:
     - modify description
     - correct typo
     - add some comment

    Signed-off-by: Minchan Kim <minchan.kim@gmail.com>

commit 01f87794eb6f04aa788b1e8f0ad9ff95357431cc
Author: Minchan Kim <minchan.kim@gmail.com>
Date:   Mon Dec 6 02:29:09 2010 +0900

    Fix checkpatch's report in swap.c

    checkpatch reports following problems.
    It's a very annoying. This patch fixes it.

    barrios@barrios-desktop:~/linux-2.6$ ./scripts/checkpatch.pl -f mm/swap.c
    WARNING: line over 80 characters
    +		if (PageLRU(page) && !PageActive(page) && !PageUnevictable(page)) {

    WARNING: EXPORT_SYMBOL(foo); should immediately follow its function/variable
    +EXPORT_SYMBOL(mark_page_accessed);

    ERROR: code indent should use tabs where possible
    +  ^I^I}$

    WARNING: please, no space before tabs
    +  ^I^I}$

    WARNING: please, no spaces at the start of a line
    +  ^I^I}$

    WARNING: EXPORT_SYMBOL(foo); should immediately follow its function/variable
    +EXPORT_SYMBOL(__pagevec_release);

    WARNING: EXPORT_SYMBOL(foo); should immediately follow its function/variable
    +EXPORT_SYMBOL(____pagevec_lru_add);

    WARNING: EXPORT_SYMBOL(foo); should immediately follow its function/variable
    +EXPORT_SYMBOL(pagevec_lookup);

    WARNING: EXPORT_SYMBOL(foo); should immediately follow its function/variable
    +EXPORT_SYMBOL(pagevec_lookup_tag);

    total: 1 errors, 8 warnings, 517 lines checked

    Signed-off-by: Minchan Kim <minchan.kim@gmail.com>